const RECIPES = [
  {
    id: "canteen-001",
    name: "番茄炒蛋（一份）",
    source: "canteen",
    mealTypes: ["lunch", "dinner"],
    calories: 210,
    protein: 10,
    carbs: 12,
    fat: 14,
    price: 4,
    place: "第一食堂 家常菜窗口",
    tags: ["少油", "无辣"],
    allergens: ["含蛋"],
    ingredients: ["番茄 150g", "鸡蛋 70g", "食用油 5g"],
    steps: [],
    cookTime: null,
    emoji: "🍅",
    imageUrl: "assets/images/photo-1512621776951-a57141f2eefd.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "canteen-002",
    name: "清炒时蔬（一份）",
    source: "canteen",
    mealTypes: ["lunch", "dinner"],
    calories: 90,
    protein: 3,
    carbs: 10,
    fat: 4,
    price: 3,
    place: "第二食堂 素菜窗口",
    tags: ["素食", "低脂", "无辣"],
    allergens: [],
    ingredients: ["时令蔬菜 200g", "食用油 3g"],
    steps: [],
    cookTime: null,
    emoji: "🥬",
    imageUrl: "assets/images/photo-1490645935967-10de6ba17061.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "canteen-003",
    name: "酸辣土豆丝（一份）",
    source: "canteen",
    mealTypes: ["lunch", "dinner"],
    calories: 150,
    protein: 2,
    carbs: 22,
    fat: 6,
    price: 3,
    place: "第一食堂 家常菜窗口",
    tags: ["素食", "低脂"],
    allergens: ["辛辣"],
    ingredients: ["土豆 200g", "青红椒 30g", "食用油 5g"],
    steps: [],
    cookTime: null,
    emoji: "🥔",
    imageUrl: "assets/images/photo-1540189549336-e6e99c3679fe.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "canteen-004",
    name: "红烧鸡腿（一只）",
    source: "canteen",
    mealTypes: ["lunch", "dinner"],
    calories: 230,
    protein: 21,
    carbs: 6,
    fat: 14,
    price: 5,
    place: "第二食堂 荤菜窗口",
    tags: ["高蛋白", "无辣"],
    allergens: [],
    ingredients: ["鸡腿 150g", "红烧汁 20g"],
    steps: [],
    cookTime: null,
    emoji: "🍗",
    imageUrl: "assets/images/photo-1555939594-58d7cb561ad1.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "canteen-005",
    name: "麻婆豆腐（一份）",
    source: "canteen",
    mealTypes: ["lunch", "dinner"],
    calories: 190,
    protein: 9,
    carbs: 10,
    fat: 13,
    price: 4,
    place: "第三食堂 川菜窗口",
    tags: ["素食", "低脂"],
    allergens: ["辛辣"],
    ingredients: ["豆腐 180g", "肉末 20g", "豆瓣酱 15g"],
    steps: [],
    cookTime: null,
    emoji: "🌶️",
    imageUrl: "assets/images/photo-1547592180-85f173990554.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "canteen-006",
    name: "清蒸鱼块（一份）",
    source: "canteen",
    mealTypes: ["lunch", "dinner"],
    calories: 170,
    protein: 21,
    carbs: 3,
    fat: 8,
    price: 6,
    place: "第三食堂 蒸菜窗口",
    tags: ["高蛋白", "少油", "无辣"],
    allergens: [],
    ingredients: ["鱼块 150g", "姜葱 10g"],
    steps: [],
    cookTime: null,
    emoji: "🐟",
    imageUrl: "assets/images/photo-1467003909585-2f8a72700288.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "takeout-001",
    name: "黄焖鸡米饭（少酱版）",
    source: "takeout",
    mealTypes: ["lunch", "dinner"],
    calories: 580,
    protein: 32,
    carbs: 68,
    fat: 20,
    price: 16,
    place: "外卖平台搜“黄焖鸡米饭”",
    tags: ["高蛋白", "无辣"],
    allergens: [],
    ingredients: ["米饭 200g", "黄焖鸡 180g", "青椒 40g", "土豆 60g"],
    steps: [],
    cookTime: null,
    emoji: "🍗",
    imageUrl: "assets/images/food/braised-chicken-rice.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-09-01"
  },
  {
    id: "takeout-002",
    name: "兰州牛肉面（外卖版）",
    source: "takeout",
    mealTypes: ["lunch", "dinner"],
    calories: 520,
    protein: 28,
    carbs: 72,
    fat: 12,
    price: 14,
    place: "外卖平台搜“兰州牛肉面”",
    tags: ["高蛋白", "无辣", "快手"],
    allergens: ["含麸质"],
    ingredients: ["拉面 220g", "牛肉片 60g", "萝卜 30g", "香菜 10g"],
    steps: [],
    cookTime: null,
    emoji: "🍜",
    imageUrl: "assets/images/food/beef-noodles.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-09-01"
  },
  {
    id: "takeout-003",
    name: "全麦三明治加美式",
    source: "takeout",
    mealTypes: ["breakfast", "lunch"],
    calories: 390,
    protein: 20,
    carbs: 46,
    fat: 13,
    price: 14,
    place: "外卖平台搜“三明治咖啡”",
    tags: ["快手", "无辣"],
    allergens: ["含蛋", "含乳", "含麸质"],
    ingredients: ["全麦面包 80g", "鸡蛋 60g", "生菜 40g", "美式咖啡 350ml"],
    steps: [],
    cookTime: null,
    emoji: "🥪",
    imageUrl: "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?auto=format&fit=crop&w=640&q=70",
    dataSource: "公开菜谱整理",
    dataUpdatedAt: "2026-08-26"
  },
  {
    id: "takeout-004",
    name: "麻辣香锅（自选少油）",
    source: "takeout",
    mealTypes: ["lunch", "dinner"],
    calories: 520,
    protein: 24,
    carbs: 42,
    fat: 28,
    price: 19,
    place: "外卖平台搜“麻辣香锅”",
    tags: ["少油"],
    allergens: ["辛辣"],
    ingredients: ["鸡胸肉 80g", "午餐肉少量 30g", "蔬菜 150g", "藕片 50g", "米饭 150g"],
    steps: [],
    cookTime: null,
    emoji: "🥘",
    imageUrl: "assets/images/food/spicy-malaxiangguo.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-09-01"
  },
  {
    id: "takeout-005",
    name: "冒菜（清汤少油）",
    source: "takeout",
    mealTypes: ["lunch", "dinner"],
    calories: 460,
    protein: 22,
    carbs: 48,
    fat: 18,
    price: 15,
    place: "外卖平台搜“冒菜”",
    tags: ["低脂", "少油"],
    allergens: ["辛辣"],
    ingredients: ["蔬菜 150g", "豆制品 60g", "鸡肉片 70g", "粉丝 50g"],
    steps: [],
    cookTime: null,
    emoji: "🍲",
    imageUrl: "assets/images/food/maocai.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-09-01"
  },
  {
    id: "takeout-006",
    name: "隆江猪脚饭（去皮少酱）",
    source: "takeout",
    mealTypes: ["lunch", "dinner"],
    calories: 620,
    protein: 30,
    carbs: 68,
    fat: 26,
    price: 18,
    place: "外卖平台搜“隆江猪脚饭”",
    tags: ["高蛋白"],
    allergens: [],
    ingredients: ["米饭 200g", "猪脚 120g（去皮）", "青菜 60g", "卤汁 15g"],
    steps: [],
    cookTime: null,
    emoji: "🍖",
    imageUrl: "assets/images/food/pig-trotter-rice.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-09-01"
  },
  {
    id: "supermarket-001",
    name: "即食鸡胸肉加玉米",
    source: "supermarket",
    mealTypes: ["lunch", "dinner", "snack"],
    snackScenes: ["strength", "cardio"],
    calories: 290,
    protein: 30,
    carbs: 30,
    fat: 5,
    price: 9.9,
    place: "超市冷藏区",
    tags: ["高蛋白", "快手"],
    allergens: [],
    ingredients: ["即食鸡胸肉 100g", "玉米 200g"],
    steps: [],
    cookTime: null,
    emoji: "🌽",
    imageUrl: "https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&w=640&q=70",
    dataSource: "公开菜谱整理",
    dataUpdatedAt: "2026-08-28"
  },
  {
    id: "supermarket-002",
    name: "全麦面包加酸奶香蕉",
    source: "supermarket",
    mealTypes: ["breakfast", "snack"],
    snackScenes: ["cardio", "study"],
    calories: 420,
    protein: 15,
    carbs: 66,
    fat: 10,
    price: 8.5,
    place: "超市烘焙区与乳品区",
    tags: ["快手", "素食"],
    allergens: ["含乳", "含麸质"],
    ingredients: ["全麦面包 80g", "无糖酸奶 150g", "香蕉 120g"],
    steps: [],
    cookTime: null,
    emoji: "🍌",
    imageUrl: "https://images.unsplash.com/photo-1494390248081-4e521a5940db?auto=format&fit=crop&w=640&q=70",
    dataSource: "公开菜谱整理",
    dataUpdatedAt: "2026-08-27"
  },
  {
    id: "supermarket-003",
    name: "关东煮萝卜鸡蛋魔芋",
    source: "supermarket",
    mealTypes: ["lunch", "dinner", "snack"],
    snackScenes: ["study", "craving"],
    calories: 260,
    protein: 16,
    carbs: 28,
    fat: 9,
    price: 7,
    place: "超市熟食区",
    tags: ["低脂", "无辣"],
    allergens: ["含蛋"],
    ingredients: ["萝卜 150g", "鸡蛋 60g", "魔芋结 100g", "昆布 20g"],
    steps: [],
    cookTime: null,
    emoji: "🍢",
    imageUrl: "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?auto=format&fit=crop&w=640&q=70",
    dataSource: "公开菜谱整理",
    dataUpdatedAt: "2026-08-26"
  },
  {
    id: "supermarket-004",
    name: "无糖豆浆茶叶蛋玉米",
    source: "supermarket",
    mealTypes: ["breakfast", "snack"],
    snackScenes: ["study", "cardio"],
    calories: 350,
    protein: 16,
    carbs: 52,
    fat: 8,
    price: 6.5,
    place: "超市早点区",
    tags: ["素食", "快手"],
    allergens: ["含蛋"],
    ingredients: ["无糖豆浆 250ml", "茶叶蛋 60g", "玉米 200g"],
    steps: [],
    cookTime: null,
    emoji: "🥚",
    imageUrl: "https://images.unsplash.com/photo-1493770348161-369560ae357d?auto=format&fit=crop&w=640&q=70",
    dataSource: "公开菜谱整理",
    dataUpdatedAt: "2026-08-25"
  },
  {
    id: "supermarket-005",
    name: "蔬菜沙拉盒加即食牛肉",
    source: "supermarket",
    mealTypes: ["lunch", "dinner"],
    calories: 330,
    protein: 28,
    carbs: 24,
    fat: 12,
    price: 12,
    place: "超市生鲜区",
    tags: ["高蛋白", "低脂"],
    allergens: [],
    ingredients: ["蔬菜沙拉 200g", "即食牛肉 80g", "油醋汁 20g"],
    steps: [],
    cookTime: null,
    emoji: "🥗",
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=640&q=70",
    dataSource: "公开菜谱整理",
    dataUpdatedAt: "2026-08-24"
  },
  {
    id: "cook-001",
    name: "番茄鸡胸荞麦面",
    source: "cook",
    mealTypes: ["lunch", "dinner"],
    calories: 430,
    protein: 34,
    carbs: 52,
    fat: 9,
    price: 10,
    place: "宿舍小锅",
    tags: ["高蛋白", "宿舍可做", "少油"],
    allergens: ["含麸质"],
    ingredients: ["荞麦面 80g", "鸡胸肉 100g", "番茄 150g", "青菜 80g"],
    steps: ["鸡胸肉切小块，用黑胡椒和少量生抽腌 10 分钟。", "小锅烧水，番茄切块先煮 3 分钟。", "下荞麦面和鸡胸肉，煮 6 分钟。", "加入青菜再煮 1 分钟，关火调味。"],
    cookTime: 25,
    emoji: "🍜",
    imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=640&q=70",
    dataSource: "公开菜谱整理",
    dataUpdatedAt: "2026-08-28"
  },
  {
    id: "cook-002",
    name: "西兰花虾仁杂粮饭",
    source: "cook",
    mealTypes: ["lunch", "dinner"],
    calories: 480,
    protein: 32,
    carbs: 58,
    fat: 11,
    price: 12,
    place: "宿舍电煮锅",
    tags: ["高蛋白", "宿舍可做"],
    allergens: ["含虾"],
    ingredients: ["杂粮饭 150g", "虾仁 100g", "西兰花 120g", "蒜 5g"],
    steps: ["杂粮饭提前煮好，或使用免煮杂粮饭。", "西兰花焯水 2 分钟捞出。", "锅底少油，下蒜末和虾仁炒熟。", "加入西兰花和杂粮饭翻匀，调味即可。"],
    cookTime: 30,
    emoji: "🦐",
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=640&q=70",
    dataSource: "公开菜谱整理",
    dataUpdatedAt: "2026-08-27"
  },
  {
    id: "cook-003",
    name: "无油煎鸡胸配蔬菜",
    source: "cook",
    mealTypes: ["lunch", "dinner"],
    calories: 390,
    protein: 36,
    carbs: 34,
    fat: 10,
    price: 9,
    place: "宿舍不粘锅",
    tags: ["高蛋白", "宿舍可做", "少油"],
    allergens: [],
    ingredients: ["鸡胸肉 150g", "黄瓜 100g", "小番茄 80g", "玉米 80g"],
    steps: ["鸡胸肉用盐和黑胡椒腌 10 分钟。", "不粘锅烧热，放入鸡胸肉盖盖小火焖煎，不用放油。", "每面煎 4 分钟，取出切条。", "配黄瓜、小番茄和熟玉米装盘。"],
    cookTime: 20,
    emoji: "🍗",
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=640&q=70",
    dataSource: "公开菜谱整理",
    dataUpdatedAt: "2026-08-26"
  },
  {
    id: "cook-004",
    name: "燕麦牛奶香蕉杯",
    source: "cook",
    mealTypes: ["breakfast", "snack"],
    snackScenes: ["cardio", "study", "craving"],
    calories: 320,
    protein: 13,
    carbs: 48,
    fat: 9,
    price: 6,
    place: "宿舍免煮",
    tags: ["快手", "宿舍可做", "素食"],
    allergens: ["含乳"],
    ingredients: ["燕麦片 40g", "牛奶 200ml", "香蕉 100g", "坚果 10g"],
    steps: ["燕麦片用牛奶泡软 5 分钟。", "香蕉切片铺在燕麦上。", "撒一点坚果碎即可。"],
    cookTime: 5,
    emoji: "🥣",
    imageUrl: "https://images.unsplash.com/photo-1494390248081-4e521a5940db?auto=format&fit=crop&w=640&q=70",
    dataSource: "公开菜谱整理",
    dataUpdatedAt: "2026-08-25"
  },
  {
    id: "cook-005",
    name: "紫菜豆腐汤加红薯",
    source: "cook",
    mealTypes: ["dinner"],
    calories: 300,
    protein: 16,
    carbs: 44,
    fat: 6,
    price: 7,
    place: "宿舍小锅",
    tags: ["低脂", "宿舍可做", "素食"],
    allergens: [],
    ingredients: ["紫菜 5g", "豆腐 150g", "红薯 150g", "虾皮 5g"],
    steps: ["红薯蒸熟或微波炉加热。", "锅中水开，下豆腐煮 3 分钟。", "加入紫菜和虾皮煮 1 分钟，调味。"],
    cookTime: 15,
    emoji: "🍲",
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=640&q=70",
    dataSource: "公开菜谱整理",
    dataUpdatedAt: "2026-08-24"
  },
  {
    id: "cook-006",
    name: "电饭煲焖鸡胸蔬菜饭",
    source: "cook",
    mealTypes: ["lunch", "dinner"],
    calories: 520,
    protein: 34,
    carbs: 60,
    fat: 13,
    price: 11,
    place: "宿舍电饭煲",
    tags: ["高蛋白", "宿舍可做", "快手"],
    allergens: [],
    ingredients: ["大米 100g", "鸡胸肉 120g", "胡萝卜 60g", "豌豆 50g"],
    steps: ["鸡胸肉切丁，用生抽和黑胡椒腌 10 分钟。", "大米洗净，加入平时 1.2 倍水量。", "铺上鸡胸肉、胡萝卜丁和豌豆。", "按煮饭键，跳闸后焖 5 分钟拌匀。"],
    cookTime: 35,
    emoji: "🍚",
    imageUrl: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=640&q=70",
    dataSource: "公开菜谱整理",
    dataUpdatedAt: "2026-08-23"
  },
  {
    id: "convenience-001",
    name: "溏心蛋即食鸡胸关东煮",
    source: "convenience",
    mealTypes: ["lunch", "dinner", "snack"],
    snackScenes: ["strength", "study"],
    calories: 340,
    protein: 30,
    carbs: 26,
    fat: 12,
    price: 11.5,
    place: "便利店热食柜",
    tags: ["高蛋白", "快手"],
    allergens: ["含蛋"],
    ingredients: ["溏心蛋 50g", "即食鸡胸肉 100g", "关东煮萝卜 150g"],
    steps: [],
    cookTime: null,
    emoji: "🍢",
    imageUrl: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=640&q=70",
    dataSource: "公开菜谱整理",
    dataUpdatedAt: "2026-08-28"
  },
  {
    id: "convenience-002",
    name: "金枪鱼饭团加无糖豆浆",
    source: "convenience",
    mealTypes: ["breakfast", "lunch"],
    calories: 420,
    protein: 17,
    carbs: 60,
    fat: 11,
    price: 8.8,
    place: "便利店饭团区",
    tags: ["快手", "无辣"],
    allergens: ["含鱼", "含乳"],
    ingredients: ["金枪鱼饭团 150g", "无糖豆浆 250ml"],
    steps: [],
    cookTime: null,
    emoji: "🍙",
    imageUrl: "https://images.unsplash.com/photo-1540914124281-342587941389?auto=format&fit=crop&w=640&q=70",
    dataSource: "公开菜谱整理",
    dataUpdatedAt: "2026-08-27"
  },
  {
    id: "convenience-003",
    name: "蔬菜沙拉加鸡胸肉",
    source: "convenience",
    mealTypes: ["lunch", "dinner"],
    calories: 330,
    protein: 28,
    carbs: 24,
    fat: 12,
    price: 13,
    place: "便利店冷藏柜",
    tags: ["高蛋白", "低脂"],
    allergens: [],
    ingredients: ["蔬菜沙拉 200g", "即食鸡胸肉 80g", "油醋汁 15g"],
    steps: [],
    cookTime: null,
    emoji: "🥗",
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=640&q=70",
    dataSource: "公开菜谱整理",
    dataUpdatedAt: "2026-08-26"
  },
  {
    id: "convenience-004",
    name: "全麦饭团酸奶水果",
    source: "convenience",
    mealTypes: ["breakfast", "snack"],
    snackScenes: ["cardio", "study", "craving"],
    calories: 410,
    protein: 14,
    carbs: 62,
    fat: 10,
    price: 10,
    place: "便利店早餐区",
    tags: ["快手", "素食"],
    allergens: ["含乳", "含麸质"],
    ingredients: ["全麦饭团 120g", "无糖酸奶 120g", "香蕉 100g"],
    steps: [],
    cookTime: null,
    emoji: "🍙",
    imageUrl: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=640&q=70",
    dataSource: "公开菜谱整理",
    dataUpdatedAt: "2026-08-25"
  },
  {
    id: "canteen-007",
    name: "鸭腿（去皮，单份）",
    source: "canteen",
    mealTypes: ["lunch", "dinner"],
    calories: 260,
    protein: 26,
    carbs: 3,
    fat: 16,
    price: 7,
    place: "第一食堂 烧腊窗口",
    tags: ["高蛋白", "少油"],
    allergens: [],
    ingredients: ["去皮鸭腿 150g", "卤汁 15g"],
    steps: [],
    cookTime: null,
    emoji: "🍗",
    imageUrl: "assets/images/photo-1555939594-58d7cb561ad1.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "canteen-008",
    name: "牛肉面（清汤少油版）",
    source: "canteen",
    mealTypes: ["lunch", "dinner"],
    calories: 520,
    protein: 28,
    carbs: 72,
    fat: 12,
    price: 11,
    place: "第二食堂 面食窗口",
    tags: ["高蛋白", "无辣", "快手"],
    allergens: ["含麸质"],
    ingredients: ["面条 200g", "牛肉 80g", "青菜 60g", "清汤 300ml"],
    steps: [],
    cookTime: null,
    emoji: "🍜",
    imageUrl: "assets/images/photo-1569718212165-3a8278d5f624.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "canteen-009",
    name: "麻辣烫（清汤少油）",
    source: "canteen",
    mealTypes: ["lunch", "dinner"],
    calories: 450,
    protein: 22,
    carbs: 50,
    fat: 16,
    price: 13,
    place: "第一食堂 麻辣烫窗口",
    tags: ["低脂", "少油"],
    allergens: ["辛辣"],
    ingredients: ["蔬菜 150g", "豆腐 60g", "鸡肉丸 50g", "粉丝 60g"],
    steps: [],
    cookTime: null,
    emoji: "🍲",
    imageUrl: "assets/images/photo-1547592180-85f173990554.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "canteen-010",
    name: "肉末蒸蛋（一份）",
    source: "canteen",
    mealTypes: ["lunch"],
    calories: 140,
    protein: 11,
    carbs: 3,
    fat: 9,
    price: 4,
    place: "第三食堂 蒸菜窗口",
    tags: ["无辣", "快手"],
    allergens: ["含蛋"],
    ingredients: ["肉末 20g", "鸡蛋 70g"],
    steps: [],
    cookTime: null,
    emoji: "🥚",
    imageUrl: "assets/images/photo-1493770348161-369560ae357d.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "canteen-011",
    name: "米饭（二两）",
    source: "canteen",
    mealTypes: ["lunch", "dinner"],
    calories: 174,
    protein: 3.9,
    carbs: 38.8,
    fat: 0.5,
    price: 1,
    place: "食堂米饭窗口",
    tags: ["无辣"],
    allergens: [],
    ingredients: ["米饭 150g"],
    steps: [],
    cookTime: null,
    emoji: "🍚",
    imageUrl: "assets/images/photo-1512058564366-18510be2db19.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "canteen-012",
    name: "杂粮饭（一份）",
    source: "canteen",
    mealTypes: ["lunch", "dinner"],
    calories: 160,
    protein: 4,
    carbs: 31,
    fat: 1.5,
    price: 2,
    place: "食堂粗粮窗口",
    tags: ["无辣"],
    allergens: [],
    ingredients: ["杂粮米 130g"],
    steps: [],
    cookTime: null,
    emoji: "🌾",
    imageUrl: "assets/images/photo-1512058564366-18510be2db19.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "canteen-013",
    name: "紫菜蛋花汤（一碗）",
    source: "canteen",
    mealTypes: ["lunch", "dinner"],
    calories: 40,
    protein: 3,
    carbs: 3,
    fat: 1,
    price: 2,
    place: "食堂汤品窗口",
    tags: ["素食", "低脂", "无辣"],
    allergens: ["含蛋"],
    ingredients: ["紫菜 5g", "鸡蛋 30g", "清汤 250ml"],
    steps: [],
    cookTime: null,
    emoji: "🍲",
    imageUrl: "assets/images/photo-1547592180-85f173990554.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "canteen-014",
    name: "玉米（一根）",
    source: "canteen",
    mealTypes: ["breakfast", "snack"],
    snackScenes: ["cardio", "study", "craving"],
    calories: 112,
    protein: 4,
    carbs: 22.8,
    fat: 1.2,
    price: 2.5,
    place: "食堂粗粮窗口",
    tags: ["素食", "低脂", "无辣"],
    allergens: [],
    ingredients: ["甜玉米 200g"],
    steps: [],
    cookTime: null,
    emoji: "🌽",
    imageUrl: "assets/images/photo-1553621042-f6e147245754.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "takeout-007",
    name: "米村拌饭（牛肉石锅拌饭）",
    source: "takeout",
    mealTypes: ["lunch", "dinner"],
    calories: 650,
    protein: 26,
    carbs: 92,
    fat: 20,
    price: 23,
    place: "外卖平台搜“石锅拌饭”",
    tags: ["高蛋白", "无辣"],
    allergens: ["含蛋"],
    ingredients: ["米饭 250g", "牛肉 80g", "菠菜 50g", "豆芽 50g", "煎蛋 50g", "韩式辣酱 20g"],
    steps: [],
    cookTime: null,
    emoji: "🍚",
    imageUrl: "assets/images/photo-1585032226651-759b368d7246.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "takeout-008",
    name: "鸡腿汉堡套餐（去酱）",
    source: "takeout",
    mealTypes: ["lunch", "dinner"],
    calories: 560,
    protein: 28,
    carbs: 62,
    fat: 22,
    price: 19,
    place: "外卖平台搜“鸡腿堡套餐”",
    tags: ["高蛋白", "快手"],
    allergens: ["含麸质", "含蛋"],
    ingredients: ["汉堡胚 80g", "鸡腿排 120g", "生菜 40g", "0糖饮料 330ml"],
    steps: [],
    cookTime: null,
    emoji: "🍔",
    imageUrl: "assets/images/photo-1568901346375-23c9450c58cd.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "takeout-009",
    name: "鸭腿饭（外卖版）",
    source: "takeout",
    mealTypes: ["lunch", "dinner"],
    calories: 640,
    protein: 32,
    carbs: 74,
    fat: 24,
    price: 17,
    place: "外卖平台搜“鸭腿饭”",
    tags: ["高蛋白"],
    allergens: [],
    ingredients: ["米饭 200g", "鸭腿 160g", "配菜 80g"],
    steps: [],
    cookTime: null,
    emoji: "🍗",
    imageUrl: "assets/images/photo-1555939594-58d7cb561ad1.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "takeout-010",
    name: "煲仔饭（少腊味版）",
    source: "takeout",
    mealTypes: ["lunch", "dinner"],
    calories: 640,
    protein: 26,
    carbs: 76,
    fat: 26,
    price: 19,
    place: "外卖平台搜“煲仔饭”",
    tags: ["无辣"],
    allergens: ["含蛋"],
    ingredients: ["米饭 220g", "腊肠 40g", "鸡蛋 60g", "青菜 80g"],
    steps: [],
    cookTime: null,
    emoji: "🍚",
    imageUrl: "assets/images/food/claypot-rice.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-09-01"
  },
  {
    id: "takeout-011",
    name: "酸菜鱼米饭（少油）",
    source: "takeout",
    mealTypes: ["lunch", "dinner"],
    calories: 600,
    protein: 32,
    carbs: 70,
    fat: 20,
    price: 21,
    place: "外卖平台搜“酸菜鱼米饭”",
    tags: ["高蛋白"],
    allergens: ["辛辣"],
    ingredients: ["米饭 200g", "鱼片 150g", "酸菜 80g", "豆芽 60g"],
    steps: [],
    cookTime: null,
    emoji: "🐟",
    imageUrl: "assets/images/food/pickled-cabbage-fish.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-09-01"
  },
  {
    id: "takeout-012",
    name: "鸡公煲（少油少辣）",
    source: "takeout",
    mealTypes: ["lunch", "dinner"],
    calories: 650,
    protein: 36,
    carbs: 60,
    fat: 26,
    price: 20,
    place: "外卖平台搜“鸡公煲”",
    tags: ["高蛋白"],
    allergens: ["辛辣"],
    ingredients: ["鸡肉 180g", "土豆 100g", "洋葱 60g", "米饭 150g"],
    steps: [],
    cookTime: null,
    emoji: "🍗",
    imageUrl: "assets/images/food/chicken-pot.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-09-01"
  },
  {
    id: "takeout-013",
    name: "麦当劳板烧鸡腿堡套餐（去酱）",
    source: "takeout",
    mealTypes: ["lunch", "dinner"],
    calories: 520,
    protein: 30,
    carbs: 52,
    fat: 20,
    price: 24,
    place: "麦当劳 外卖/自取",
    tags: ["高蛋白", "快手"],
    allergens: ["含麸质", "含蛋"],
    ingredients: ["板烧鸡腿堡 1个（去酱）", "0糖饮料 330ml"],
    steps: [],
    cookTime: null,
    emoji: "🍔",
    imageUrl: "assets/images/food/burger-mcdonalds.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-09-01"
  },
  {
    id: "takeout-014",
    name: "肯德基新奥尔良烤鸡腿堡套餐（去酱）",
    source: "takeout",
    mealTypes: ["lunch", "dinner"],
    calories: 500,
    protein: 28,
    carbs: 50,
    fat: 20,
    price: 23,
    place: "肯德基 外卖/自取",
    tags: ["高蛋白", "快手"],
    allergens: ["含麸质", "含蛋"],
    ingredients: ["新奥尔良烤鸡腿堡 1个（去酱）", "0糖饮料 330ml"],
    steps: [],
    cookTime: null,
    emoji: "🍔",
    imageUrl: "assets/images/food/burger-kfc.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-09-01"
  },
  {
    id: "takeout-015",
    name: "汉堡王皇堡套餐（去酱）",
    source: "takeout",
    mealTypes: ["lunch", "dinner"],
    calories: 640,
    protein: 30,
    carbs: 58,
    fat: 32,
    price: 28,
    place: "汉堡王 外卖/自取",
    tags: ["高蛋白", "快手"],
    allergens: ["含麸质", "含乳"],
    ingredients: ["皇堡 1个（去酱）", "0糖饮料 330ml"],
    steps: [],
    cookTime: null,
    emoji: "🍔",
    imageUrl: "assets/images/food/burger-bk.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-09-01"
  },
  {
    id: "takeout-016",
    name: "华莱士香辣鸡腿堡套餐（去酱）",
    source: "takeout",
    mealTypes: ["lunch", "dinner"],
    calories: 540,
    protein: 26,
    carbs: 56,
    fat: 24,
    price: 15,
    place: "华莱士 外卖/自取",
    tags: ["高蛋白", "快手"],
    allergens: ["含麸质", "含蛋", "辛辣"],
    ingredients: ["香辣鸡腿堡 1个（去酱）", "0糖饮料 330ml"],
    steps: [],
    cookTime: null,
    emoji: "🍔",
    imageUrl: "assets/images/food/burger-hualai.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-09-01"
  },
  {
    id: "takeout-017",
    name: "塔斯汀中国汉堡套餐（去皮去酱）",
    source: "takeout",
    mealTypes: ["lunch", "dinner"],
    calories: 560,
    protein: 28,
    carbs: 60,
    fat: 22,
    price: 18,
    place: "塔斯汀 外卖/自取",
    tags: ["高蛋白", "快手"],
    allergens: ["含麸质", "含蛋"],
    ingredients: ["塔斯汀汉堡 1个（去皮去酱）", "0糖饮料 330ml"],
    steps: [],
    cookTime: null,
    emoji: "🍔",
    imageUrl: "assets/images/food/burger-tastien.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-09-01"
  },
  {
    id: "takeout-018",
    name: "德克士脆皮手枪腿汉堡套餐",
    source: "takeout",
    mealTypes: ["lunch", "dinner"],
    calories: 660,
    protein: 30,
    carbs: 56,
    fat: 36,
    price: 25,
    place: "德克士 外卖/自取",
    tags: ["高蛋白", "快手"],
    allergens: ["含麸质", "含蛋"],
    ingredients: ["脆皮手枪腿汉堡 1个", "0糖饮料 330ml"],
    steps: [],
    cookTime: null,
    emoji: "🍔",
    imageUrl: "assets/images/food/burger-dicos.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-09-01"
  },
  {
    id: "supermarket-006",
    name: "即食饭团加鸡胸蛋白棒",
    source: "supermarket",
    mealTypes: ["breakfast", "lunch", "snack"],
    snackScenes: ["strength", "cardio"],
    calories: 380,
    protein: 26,
    carbs: 46,
    fat: 9,
    price: 12,
    place: "超市冷藏区",
    tags: ["高蛋白", "快手"],
    allergens: ["含麸质"],
    ingredients: ["即食饭团 130g", "鸡胸蛋白棒 35g"],
    steps: [],
    cookTime: null,
    emoji: "🍙",
    imageUrl: "assets/images/photo-1540914124281-342587941389.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "supermarket-007",
    name: "冷冻杂粮包加酸奶",
    source: "supermarket",
    mealTypes: ["breakfast", "snack"],
    snackScenes: ["cardio", "study"],
    calories: 360,
    protein: 13,
    carbs: 58,
    fat: 8,
    price: 9,
    place: "超市冷冻区与乳品区",
    tags: ["快手", "素食"],
    allergens: ["含乳", "含麸质"],
    ingredients: ["杂粮包 100g", "无糖酸奶 150g", "蓝莓 30g"],
    steps: [],
    cookTime: null,
    emoji: "🍞",
    imageUrl: "assets/images/photo-1494390248081-4e521a5940db.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "supermarket-008",
    name: "即食牛肉蔬菜杯",
    source: "supermarket",
    mealTypes: ["lunch", "dinner", "snack"],
    snackScenes: ["strength", "study"],
    calories: 340,
    protein: 30,
    carbs: 22,
    fat: 12,
    price: 14,
    place: "超市冷藏柜",
    tags: ["高蛋白", "低脂"],
    allergens: [],
    ingredients: ["即食牛肉 90g", "蔬菜杯 180g", "油醋汁 15g"],
    steps: [],
    cookTime: null,
    emoji: "🥗",
    imageUrl: "assets/images/photo-1512621776951-a57141f2eefd.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "cook-007",
    name: "电饭煲牛肉焖饭",
    source: "cook",
    mealTypes: ["lunch", "dinner"],
    calories: 540,
    protein: 28,
    carbs: 66,
    fat: 16,
    price: 13,
    place: "宿舍电饭煲",
    tags: ["高蛋白", "宿舍可做", "快手"],
    allergens: [],
    ingredients: ["大米 120g", "牛肉 100g", "胡萝卜 60g", "香菇 30g"],
    steps: ["牛肉切丁，用生抽和黑胡椒腌 10 分钟。", "大米洗净，加入平时 1.2 倍水量。", "铺上牛肉、胡萝卜和香菇。", "按煮饭键，跳闸后焖 5 分钟拌匀。"],
    cookTime: 35,
    emoji: "🍚",
    imageUrl: "assets/images/photo-1512058564366-18510be2db19.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "cook-008",
    name: "微波炉牛奶燕麦蒸蛋",
    source: "cook",
    mealTypes: ["breakfast", "snack"],
    snackScenes: ["cardio", "study"],
    calories: 330,
    protein: 15,
    carbs: 46,
    fat: 10,
    price: 7,
    place: "宿舍微波炉",
    tags: ["快手", "宿舍可做", "素食"],
    allergens: ["含乳", "含蛋"],
    ingredients: ["燕麦片 35g", "牛奶 200ml", "鸡蛋 1个", "苹果丁 40g"],
    steps: ["燕麦片加牛奶拌匀，打入鸡蛋搅匀。", "微波炉高火 2 分钟，取出搅拌一次。", "再加热 1 分钟，放上苹果丁。"],
    cookTime: 8,
    emoji: "🥣",
    imageUrl: "assets/images/photo-1494390248081-4e521a5940db.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "cook-009",
    name: "金枪鱼玉米沙拉杯",
    source: "cook",
    mealTypes: ["lunch", "snack"],
    snackScenes: ["cardio", "study", "craving"],
    calories: 300,
    protein: 22,
    carbs: 30,
    fat: 9,
    price: 10,
    place: "宿舍免煮",
    tags: ["高蛋白", "宿舍可做", "快手"],
    allergens: ["含鱼"],
    ingredients: ["金枪鱼罐头 80g", "玉米粒 80g", "生菜 100g", "油醋汁 15g"],
    steps: ["金枪鱼沥干水分。", "生菜撕小段，和玉米粒一起装杯。", "加入金枪鱼和油醋汁拌匀。"],
    cookTime: 5,
    emoji: "🥗",
    imageUrl: "assets/images/photo-1490645935967-10de6ba17061.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "cook-010",
    name: "电煮锅番茄豆腐汤",
    source: "cook",
    mealTypes: ["lunch", "dinner"],
    calories: 200,
    protein: 12,
    carbs: 16,
    fat: 9,
    price: 8,
    place: "宿舍小功率电煮锅（300W）",
    tags: ["低脂", "宿舍可做", "快手", "限电友好"],
    allergens: [],
    ingredients: ["番茄 200g", "豆腐 150g", "青菜 80g", "盐/胡椒少许"],
    steps: ["番茄切块，电煮锅加水煮 3 分钟。", "下豆腐和青菜再煮 4 分钟。", "加盐和胡椒调味即可。"],
    cookTime: 15,
    emoji: "🍲",
    imageUrl: "assets/images/photo-1547592180-85f173990554.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "cook-011",
    name: "微波炉蒸紫薯加鸡蛋",
    source: "cook",
    mealTypes: ["breakfast", "snack"],
    snackScenes: ["cardio", "study"],
    calories: 280,
    protein: 10,
    carbs: 52,
    fat: 4,
    price: 5,
    place: "宿舍微波炉",
    tags: ["素食", "宿舍可做", "快手", "限电友好"],
    allergens: ["含蛋"],
    ingredients: ["紫薯 200g", "鸡蛋 1个"],
    steps: ["紫薯洗净，微波炉高火 6-8 分钟至软。", "鸡蛋加少许水打散，中火蒸 2 分钟。", "紫薯和蒸蛋一起装盘。"],
    cookTime: 12,
    emoji: "🍠",
    imageUrl: "assets/images/photo-1493770348161-369560ae357d.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "cook-012",
    name: "免煮隔夜燕麦杯",
    source: "cook",
    mealTypes: ["breakfast", "snack"],
    snackScenes: ["cardio", "study", "craving"],
    calories: 300,
    protein: 14,
    carbs: 42,
    fat: 8,
    price: 7,
    place: "宿舍冰箱冷藏过夜",
    tags: ["素食", "宿舍可做", "快手", "限电友好"],
    allergens: ["含乳"],
    ingredients: ["燕麦片 40g", "牛奶 200ml", "奇亚籽 5g", "香蕉 80g"],
    steps: ["燕麦和奇亚籽加牛奶拌匀。", "盖好放冰箱冷藏过夜。", "早上加香蕉片直接吃。"],
    cookTime: 5,
    emoji: "🥣",
    imageUrl: "assets/images/photo-1494390248081-4e521a5940db.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "cook-013",
    name: "全麦三明治（宿舍免煮）",
    source: "cook",
    mealTypes: ["breakfast", "lunch", "snack"],
    snackScenes: ["study", "cardio"],
    calories: 350,
    protein: 22,
    carbs: 38,
    fat: 12,
    price: 9,
    place: "宿舍免煮",
    tags: ["高蛋白", "宿舍可做", "快手", "限电友好"],
    allergens: ["含麸质", "含蛋"],
    ingredients: ["全麦面包 80g", "鸡蛋 1个", "鸡胸肉片 40g", "生菜 40g"],
    steps: ["鸡蛋煮熟或直接用即食水煮蛋。", "全麦面包夹鸡胸肉片、蛋和生菜。", "对角切开即可。"],
    cookTime: 8,
    emoji: "🥪",
    imageUrl: "assets/images/photo-1482049016688-2d3e1b311543.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "cook-014",
    name: "魔芋凉拌黄瓜虾仁",
    source: "cook",
    mealTypes: ["lunch", "dinner", "snack"],
    snackScenes: ["strength", "cardio", "study"],
    calories: 220,
    protein: 20,
    carbs: 18,
    fat: 6,
    price: 11,
    place: "宿舍免煮",
    tags: ["高蛋白", "低脂", "宿舍可做", "限电友好"],
    allergens: ["含虾"],
    ingredients: ["魔芋结 150g", "黄瓜 100g", "虾仁 80g", "油醋汁 15g"],
    steps: ["虾仁和魔芋结开水焯 2 分钟。", "黄瓜拍碎切段。", "全部拌匀加油醋汁。"],
    cookTime: 10,
    emoji: "🥒",
    imageUrl: "assets/images/photo-1490645935967-10de6ba17061.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "cook-015",
    name: "电煮锅荞麦面荷包蛋",
    source: "cook",
    mealTypes: ["lunch", "dinner"],
    calories: 380,
    protein: 22,
    carbs: 52,
    fat: 10,
    price: 8,
    place: "宿舍小功率电煮锅（300W）",
    tags: ["高蛋白", "宿舍可做", "限电友好"],
    allergens: ["含麸质", "含蛋"],
    ingredients: ["荞麦面 80g", "鸡蛋 1个", "青菜 60g", "生抽少许"],
    steps: ["水开下面煮 4 分钟。", "打入鸡蛋，加青菜再煮 2 分钟。", "加少量生抽调味。"],
    cookTime: 12,
    emoji: "🍜",
    imageUrl: "assets/images/photo-1569718212165-3a8278d5f624.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "cook-016",
    name: "酸奶水果坚果杯（免煮）",
    source: "cook",
    mealTypes: ["breakfast", "snack"],
    snackScenes: ["study", "craving"],
    calories: 280,
    protein: 9,
    carbs: 38,
    fat: 10,
    price: 8,
    place: "宿舍免煮",
    tags: ["素食", "宿舍可做", "快手", "限电友好"],
    allergens: ["含乳", "含坚果"],
    ingredients: ["无糖酸奶 150g", "苹果 100g", "香蕉 60g", "坚果碎 10g"],
    steps: ["水果切块。", "酸奶打底，铺水果，撒坚果碎。"],
    cookTime: 5,
    emoji: "🍎",
    imageUrl: "assets/images/photo-1519708227418-c8fd9a32b7a2.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "convenience-005",
    name: "便利店汉堡加无糖饮料",
    source: "convenience",
    mealTypes: ["lunch", "dinner", "snack"],
    snackScenes: ["craving", "study"],
    calories: 520,
    protein: 22,
    carbs: 58,
    fat: 22,
    price: 12.5,
    place: "便利店热食柜",
    tags: ["快手"],
    allergens: ["含麸质", "含蛋"],
    ingredients: ["汉堡 150g", "0糖饮料 330ml"],
    steps: [],
    cookTime: null,
    emoji: "🍔",
    imageUrl: "assets/images/photo-1568901346375-23c9450c58cd.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "convenience-006",
    name: "鸭肉饭团加关东煮",
    source: "convenience",
    mealTypes: ["lunch", "dinner", "snack"],
    snackScenes: ["study", "craving"],
    calories: 420,
    protein: 20,
    carbs: 54,
    fat: 13,
    price: 10.5,
    place: "便利店饭团区",
    tags: ["快手", "无辣"],
    allergens: ["含麸质", "含蛋"],
    ingredients: ["鸭肉饭团 120g", "关东煮萝卜 120g", "溏心蛋 50g"],
    steps: [],
    cookTime: null,
    emoji: "🍙",
    imageUrl: "assets/images/photo-1540914124281-342587941389.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "convenience-007",
    name: "即食鸡胸加玉米杯",
    source: "convenience",
    mealTypes: ["lunch", "dinner", "snack"],
    snackScenes: ["strength", "cardio"],
    calories: 330,
    protein: 28,
    carbs: 34,
    fat: 6,
    price: 11,
    place: "便利店冷藏柜",
    tags: ["高蛋白", "低脂", "快手"],
    allergens: [],
    ingredients: ["即食鸡胸肉 100g", "玉米杯 180g"],
    steps: [],
    cookTime: null,
    emoji: "🌽",
    imageUrl: "assets/images/photo-1553621042-f6e147245754.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "bakery-001",
    name: "全麦贝果加无糖豆浆",
    source: "bakery",
    mealTypes: ["breakfast", "snack"],
    snackScenes: ["study", "craving"],
    calories: 320,
    protein: 12,
    carbs: 48,
    fat: 8,
    price: 8,
    place: "校园烘焙店",
    tags: ["素食", "快手"],
    allergens: ["含麸质", "含乳"],
    ingredients: ["全麦贝果 100g", "无糖豆浆 250ml"],
    steps: [],
    cookTime: null,
    emoji: "🥯",
    imageUrl: "assets/images/photo-1482049016688-2d3e1b311543.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "bakery-002",
    name: "南瓜欧包加酸奶杯",
    source: "bakery",
    mealTypes: ["breakfast", "snack"],
    snackScenes: ["study", "craving"],
    calories: 360,
    protein: 12,
    carbs: 58,
    fat: 9,
    price: 10,
    place: "校园烘焙店",
    tags: ["素食", "低脂"],
    allergens: ["含乳", "含麸质"],
    ingredients: ["南瓜欧包 110g", "无糖酸奶 150g"],
    steps: [],
    cookTime: null,
    emoji: "🥖",
    imageUrl: "assets/images/photo-1494390248081-4e521a5940db.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "fruit-001",
    name: "水果拼盘加坚果",
    source: "fruit",
    mealTypes: ["snack"],
    snackScenes: ["cardio", "study", "craving"],
    calories: 250,
    protein: 5,
    carbs: 38,
    fat: 9,
    price: 8,
    place: "校园水果店",
    tags: ["素食", "低脂"],
    allergens: ["含坚果"],
    ingredients: ["当季水果 250g", "坚果碎 10g"],
    steps: [],
    cookTime: null,
    emoji: "🍎",
    imageUrl: "assets/images/photo-1490645935967-10de6ba17061.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "fruit-002",
    name: "酸奶水果杯",
    source: "fruit",
    mealTypes: ["breakfast", "snack"],
    snackScenes: ["cardio", "study"],
    calories: 280,
    protein: 8,
    carbs: 42,
    fat: 8,
    price: 9,
    place: "校园水果店",
    tags: ["素食", "快手"],
    allergens: ["含乳"],
    ingredients: ["无糖酸奶 150g", "香蕉 80g", "蓝莓 40g"],
    steps: [],
    cookTime: null,
    emoji: "🥣",
    imageUrl: "assets/images/photo-1519708227418-c8fd9a32b7a2.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "stall-001",
    name: "烤冷面（少酱少油版）",
    source: "stall",
    mealTypes: ["lunch", "dinner", "snack"],
    snackScenes: ["craving", "study"],
    calories: 430,
    protein: 16,
    carbs: 60,
    fat: 15,
    price: 8,
    place: "校门口小吃摊",
    tags: ["少油"],
    allergens: ["含蛋", "含麸质"],
    ingredients: ["冷面 200g", "鸡蛋 1个", "生菜 40g", "酱料减半"],
    steps: [],
    cookTime: null,
    emoji: "🍳",
    imageUrl: "assets/images/photo-1504674900247-0877df9cc836.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "stall-002",
    name: "关东煮蔬菜串",
    source: "stall",
    mealTypes: ["dinner", "snack"],
    snackScenes: ["study", "craving"],
    calories: 220,
    protein: 12,
    carbs: 24,
    fat: 8,
    price: 6,
    place: "校门口夜宵摊",
    tags: ["低脂", "无辣"],
    allergens: ["含蛋"],
    ingredients: ["萝卜 120g", "魔芋结 100g", "溏心蛋 50g", "海带结 40g"],
    steps: [],
    cookTime: null,
    emoji: "🍢",
    imageUrl: "assets/images/photo-1476224203421-9ac39bcb3327.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "canteen-015",
    name: "宫保鸡丁（一份）",
    source: "canteen",
    mealTypes: ["lunch", "dinner"],
    calories: 230,
    protein: 16,
    carbs: 10,
    fat: 14,
    price: 5,
    place: "第二食堂 川菜窗口",
    tags: ["高蛋白"],
    allergens: ["辛辣"],
    ingredients: ["鸡丁 120g", "花生 20g", "黄瓜丁 60g"],
    steps: [],
    cookTime: null,
    emoji: "🍗",
    imageUrl: "assets/images/photo-1555939594-58d7cb561ad1.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "canteen-016",
    name: "鱼香肉丝（一份）",
    source: "canteen",
    mealTypes: ["lunch", "dinner"],
    calories: 210,
    protein: 12,
    carbs: 14,
    fat: 12,
    price: 5,
    place: "第三食堂 家常菜窗口",
    tags: ["无辣"],
    allergens: ["辛辣"],
    ingredients: ["瘦肉丝 100g", "木耳 30g", "胡萝卜丝 50g", "青椒丝 40g"],
    steps: [],
    cookTime: null,
    emoji: "🥢",
    imageUrl: "assets/images/photo-1504674900247-0877df9cc836.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "canteen-017",
    name: "红烧茄子（一份）",
    source: "canteen",
    mealTypes: ["lunch", "dinner"],
    calories: 200,
    protein: 3,
    carbs: 14,
    fat: 15,
    price: 4,
    place: "第一食堂 家常菜窗口",
    tags: ["素食"],
    allergens: [],
    ingredients: ["茄子 200g", "蒜末 10g", "生抽少许"],
    steps: [],
    cookTime: null,
    emoji: "🍆",
    imageUrl: "assets/images/photo-1540189549336-e6e99c3679fe.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "canteen-018",
    name: "土豆炖牛肉（一份）",
    source: "canteen",
    mealTypes: ["lunch", "dinner"],
    calories: 260,
    protein: 18,
    carbs: 14,
    fat: 14,
    price: 7,
    place: "第二食堂 荤菜窗口",
    tags: ["高蛋白", "无辣"],
    allergens: [],
    ingredients: ["牛肉 100g", "土豆 150g", "胡萝卜 50g"],
    steps: [],
    cookTime: null,
    emoji: "🥘",
    imageUrl: "assets/images/photo-1512058564366-18510be2db19.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "canteen-019",
    name: "木须肉（一份）",
    source: "canteen",
    mealTypes: ["lunch", "dinner"],
    calories: 230,
    protein: 14,
    carbs: 10,
    fat: 15,
    price: 6,
    place: "第三食堂 家常菜窗口",
    tags: ["无辣"],
    allergens: ["含蛋"],
    ingredients: ["瘦肉片 80g", "鸡蛋 60g", "木耳 30g", "黄瓜片 50g"],
    steps: [],
    cookTime: null,
    emoji: "🍳",
    imageUrl: "assets/images/photo-1493770348161-369560ae357d.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "canteen-020",
    name: "蛋炒饭（少油版）",
    source: "canteen",
    mealTypes: ["lunch", "dinner"],
    calories: 320,
    protein: 9,
    carbs: 48,
    fat: 10,
    price: 6,
    place: "第一食堂 炒饭窗口",
    tags: ["少油", "无辣"],
    allergens: ["含蛋"],
    ingredients: ["米饭 200g", "鸡蛋 60g", "玉米粒 30g", "豌豆 30g"],
    steps: [],
    cookTime: null,
    emoji: "🍚",
    imageUrl: "assets/images/photo-1512058564366-18510be2db19.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "canteen-021",
    name: "绿豆汤（一碗）",
    source: "canteen",
    mealTypes: ["lunch", "dinner", "snack"],
    snackScenes: ["study", "craving"],
    calories: 60,
    protein: 2,
    carbs: 12,
    fat: 0.5,
    price: 2,
    place: "食堂汤品窗口",
    tags: ["素食", "低脂", "无辣"],
    allergens: [],
    ingredients: ["绿豆 30g", "水 250ml"],
    steps: [],
    cookTime: null,
    emoji: "🥣",
    imageUrl: "assets/images/photo-1547592180-85f173990554.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "single-001",
    name: "馒头（一个）",
    source: "single",
    mealTypes: ["breakfast", "lunch", "dinner"],
    calories: 223,
    protein: 7,
    carbs: 47,
    fat: 1.1,
    price: 1,
    place: "食堂/超市 面点区",
    tags: ["素食", "无辣"],
    allergens: ["含麸质"],
    ingredients: ["馒头 100g"],
    steps: [],
    cookTime: null,
    emoji: "🍞",
    imageUrl: "assets/images/photo-1482049016688-2d3e1b311543.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "single-002",
    name: "牛油果（半个）",
    source: "single",
    mealTypes: ["breakfast", "snack"],
    snackScenes: ["cardio", "study"],
    calories: 120,
    protein: 1.5,
    carbs: 6,
    fat: 11,
    price: 5,
    place: "超市水果区",
    tags: ["高纤维", "素食"],
    allergens: [],
    ingredients: ["牛油果 75g"],
    steps: [],
    cookTime: null,
    emoji: "🥑",
    imageUrl: "assets/images/photo-1519708227418-c8fd9a32b7a2.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "single-003",
    name: "蒸土豆（一个）",
    source: "single",
    mealTypes: ["lunch", "dinner", "snack"],
    snackScenes: ["cardio", "study", "craving"],
    calories: 100,
    protein: 2.6,
    carbs: 23,
    fat: 0.1,
    price: 2,
    place: "食堂粗粮窗口/超市",
    tags: ["素食", "低脂", "无辣"],
    allergens: [],
    ingredients: ["土豆 150g"],
    steps: [],
    cookTime: null,
    emoji: "🥔",
    imageUrl: "assets/images/photo-1490645935967-10de6ba17061.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "single-004",
    name: "水煮蛋（一个）",
    source: "single",
    mealTypes: ["breakfast", "snack"],
    snackScenes: ["strength", "cardio", "study"],
    calories: 78,
    protein: 6.3,
    carbs: 0.6,
    fat: 5.3,
    price: 1.5,
    place: "食堂早点窗口/超市",
    tags: ["高蛋白", "素食", "无辣"],
    allergens: ["含蛋"],
    ingredients: ["鸡蛋 60g"],
    steps: [],
    cookTime: null,
    emoji: "🥚",
    imageUrl: "assets/images/photo-1493770348161-369560ae357d.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "single-005",
    name: "无糖豆浆（一杯）",
    source: "single",
    mealTypes: ["breakfast", "snack"],
    snackScenes: ["cardio", "study"],
    calories: 78,
    protein: 7.5,
    carbs: 3,
    fat: 4,
    price: 2.5,
    place: "食堂早点窗口/便利店",
    tags: ["素食", "无辣"],
    allergens: [],
    ingredients: ["无糖豆浆 250ml"],
    steps: [],
    cookTime: null,
    emoji: "🧋",
    imageUrl: "assets/images/photo-1519708227418-c8fd9a32b7a2.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "single-006",
    name: "香蕉（一根）",
    source: "single",
    mealTypes: ["breakfast", "snack"],
    snackScenes: ["cardio", "study", "craving"],
    calories: 112,
    protein: 1.7,
    carbs: 26.4,
    fat: 0.2,
    price: 2,
    place: "超市水果区",
    tags: ["素食", "无辣"],
    allergens: [],
    ingredients: ["香蕉 120g"],
    steps: [],
    cookTime: null,
    emoji: "🍌",
    imageUrl: "assets/images/photo-1494390248081-4e521a5940db.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "single-007",
    name: "苹果（一个）",
    source: "single",
    mealTypes: ["snack"],
    snackScenes: ["cardio", "study", "craving"],
    calories: 104,
    protein: 0.6,
    carbs: 27.6,
    fat: 0.4,
    price: 3,
    place: "超市水果区",
    tags: ["素食", "无辣"],
    allergens: [],
    ingredients: ["苹果 200g"],
    steps: [],
    cookTime: null,
    emoji: "🍎",
    imageUrl: "assets/images/photo-1490645935967-10de6ba17061.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "single-008",
    name: "全麦面包（两片）",
    source: "single",
    mealTypes: ["breakfast", "snack"],
    snackScenes: ["cardio", "study"],
    calories: 197,
    protein: 8,
    carbs: 36.8,
    fat: 2.6,
    price: 3,
    place: "超市烘焙区",
    tags: ["素食", "快手"],
    allergens: ["含麸质"],
    ingredients: ["全麦面包 80g"],
    steps: [],
    cookTime: null,
    emoji: "🍞",
    imageUrl: "assets/images/photo-1482049016688-2d3e1b311543.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "single-009",
    name: "纯牛奶（一杯）",
    source: "single",
    mealTypes: ["breakfast", "snack"],
    snackScenes: ["strength", "study"],
    calories: 135,
    protein: 7.5,
    carbs: 12,
    fat: 8,
    price: 3,
    place: "食堂/便利店",
    tags: ["高蛋白", "素食"],
    allergens: ["含乳"],
    ingredients: ["纯牛奶 250ml"],
    steps: [],
    cookTime: null,
    emoji: "🥛",
    imageUrl: "assets/images/photo-1494390248081-4e521a5940db.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "single-010",
    name: "蒸南瓜（一份）",
    source: "single",
    mealTypes: ["breakfast", "dinner", "snack"],
    snackScenes: ["study", "craving"],
    calories: 60,
    protein: 1.6,
    carbs: 14,
    fat: 0.2,
    price: 2,
    place: "食堂粗粮窗口",
    tags: ["素食", "低脂", "无辣"],
    allergens: [],
    ingredients: ["南瓜 200g"],
    steps: [],
    cookTime: null,
    emoji: "🎃",
    imageUrl: "assets/images/photo-1493770348161-369560ae357d.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "single-011",
    name: "黄瓜（一根）",
    source: "single",
    mealTypes: ["snack"],
    snackScenes: ["cardio", "study", "craving"],
    calories: 22,
    protein: 1,
    carbs: 5.3,
    fat: 0.2,
    price: 1.5,
    place: "超市生鲜区",
    tags: ["素食", "低脂", "无辣"],
    allergens: [],
    ingredients: ["黄瓜 150g"],
    steps: [],
    cookTime: null,
    emoji: "🥒",
    imageUrl: "assets/images/photo-1490645935967-10de6ba17061.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  },
  {
    id: "single-012",
    name: "燕麦粥（一碗）",
    source: "single",
    mealTypes: ["breakfast", "snack"],
    snackScenes: ["cardio", "study"],
    calories: 150,
    protein: 5,
    carbs: 27,
    fat: 2.5,
    price: 3,
    place: "食堂早点/宿舍免煮",
    tags: ["素食", "低脂"],
    allergens: [],
    ingredients: ["燕麦 30g", "水 250ml"],
    steps: [],
    cookTime: null,
    emoji: "🥣",
    imageUrl: "assets/images/photo-1494390248081-4e521a5940db.jpg",
    dataSource: "公开营养数据整理（估算）",
    dataUpdatedAt: "2026-08-31"
  }
];

const FOODS = [
  { name: "米饭", unit: "碗", grams: 150, kcal: 116, p: 2.6, c: 25.9, f: 0.3, emoji: "🍚" },
  { name: "馒头", unit: "个", grams: 100, kcal: 223, p: 7, c: 47, f: 1.1, emoji: "🍞" },
  { name: "鸡胸肉", unit: "块", grams: 120, kcal: 133, p: 24.6, c: 2.5, f: 2.6, emoji: "🍗" },
  { name: "鸡蛋", unit: "个", grams: 70, kcal: 144, p: 13.3, c: 2.8, f: 8.8, emoji: "🥚" },
  { name: "西兰花", unit: "份", grams: 150, kcal: 34, p: 4.4, c: 6.6, f: 0.4, emoji: "🥦" },
  { name: "西红柿", unit: "个", grams: 150, kcal: 15, p: 0.9, c: 3.3, f: 0.2, emoji: "🍅" },
  { name: "黄瓜", unit: "根", grams: 150, kcal: 15, p: 0.7, c: 2.9, f: 0.2, emoji: "🥒" },
  { name: "玉米", unit: "根", grams: 200, kcal: 112, p: 4, c: 22.8, f: 1.2, emoji: "🌽" },
  { name: "红薯", unit: "个", grams: 150, kcal: 86, p: 1.6, c: 20.1, f: 0.1, emoji: "🍠" },
  { name: "燕麦片", unit: "碗", grams: 40, kcal: 377, p: 10.1, c: 66.3, f: 6.7, emoji: "🥣" },
  { name: "牛奶", unit: "杯", grams: 250, kcal: 54, p: 3, c: 4.8, f: 3.2, emoji: "🥛" },
  { name: "无糖豆浆", unit: "杯", grams: 250, kcal: 31, p: 3, c: 1.2, f: 1.6, emoji: "🧋" },
  { name: "香蕉", unit: "根", grams: 120, kcal: 93, p: 1.4, c: 22, f: 0.2, emoji: "🍌" },
  { name: "苹果", unit: "个", grams: 200, kcal: 52, p: 0.3, c: 13.8, f: 0.2, emoji: "🍎" },
  { name: "全麦面包", unit: "片", grams: 40, kcal: 246, p: 10, c: 46, f: 3.2, emoji: "🍞" },
  { name: "虾仁", unit: "份", grams: 100, kcal: 93, p: 18.6, c: 2.8, f: 0.8, emoji: "🦐" },
  { name: "龙利鱼", unit: "份", grams: 120, kcal: 83, p: 17.2, c: 0, f: 1.2, emoji: "🐟" },
  { name: "豆腐", unit: "份", grams: 150, kcal: 82, p: 8.1, c: 4.2, f: 4.2, emoji: "🍲" },
  { name: "荞麦面", unit: "碗", grams: 180, kcal: 340, p: 11, c: 70, f: 2.5, emoji: "🍜" },
  { name: "炒青菜", unit: "份", grams: 200, kcal: 70, p: 3, c: 8, f: 3.5, emoji: "🥬" },
  { name: "番茄炒蛋", unit: "份", grams: 200, kcal: 105, p: 5, c: 6, f: 7, emoji: "🍅" },
  { name: "清炒时蔬", unit: "份", grams: 200, kcal: 45, p: 1.5, c: 5, f: 2, emoji: "🥬" },
  { name: "酸辣土豆丝", unit: "份", grams: 200, kcal: 75, p: 1, c: 11, f: 3, emoji: "🥔" },
  { name: "红烧鸡腿", unit: "只", grams: 150, kcal: 153, p: 14, c: 4, f: 9, emoji: "🍗" },
  { name: "麻婆豆腐", unit: "份", grams: 200, kcal: 95, p: 4.5, c: 5, f: 6.5, emoji: "🌶️" },
  { name: "清蒸鱼块", unit: "份", grams: 150, kcal: 113, p: 14, c: 2, f: 5.3, emoji: "🐟" },
  { name: "宫保鸡丁", unit: "份", grams: 200, kcal: 160, p: 14, c: 8, f: 9, emoji: "🍗" },
  { name: "紫菜蛋花汤", unit: "碗", grams: 250, kcal: 16, p: 1.2, c: 1.2, f: 0.4, emoji: "🍲" },
  { name: "茶叶蛋", unit: "个", grams: 60, kcal: 145, p: 12, c: 2, f: 9, emoji: "🥚" },
  { name: "蒸红薯", unit: "个", grams: 150, kcal: 57, p: 1.1, c: 13.4, f: 0.1, emoji: "🍠" },
  { name: "鸡腿", unit: "只", grams: 150, kcal: 181, p: 20, c: 0, f: 11, emoji: "🍗" },
  { name: "卤牛肉", unit: "份", grams: 100, kcal: 246, p: 33, c: 2, f: 12, emoji: "🥩" },
  { name: "油条", unit: "根", grams: 80, kcal: 388, p: 6.9, c: 51, f: 17.6, emoji: "🥖" },
  { name: "无糖酸奶", unit: "杯", grams: 150, kcal: 62, p: 3.2, c: 7, f: 3, emoji: "🥛" },
  { name: "坚果混合", unit: "小把", grams: 20, kcal: 600, p: 15, c: 20, f: 50, emoji: "🥜" }
];

// 菜谱图已本地化，离线也能完整展示；原远程地址保留在 data.js 源数据中作为来源记录。
for (const recipe of RECIPES) {
  const match = /^https:\/\/images\.unsplash\.com\/(photo-[^?]+)\?/.exec(recipe.imageUrl || "");
  if (match) recipe.imageUrl = `assets/images/${match[1]}.jpg`;
}

// 菜名匹配图（来自 360 图片公开检索，本地缓存供离线使用），逐菜谱覆盖泛化图。
const RECIPE_FOOD_IMAGES = {
  "canteen-001": "assets/images/food/tomato-egg.jpg",
  "canteen-002": "assets/images/food/stir-fried-vegetables.jpg",
  "canteen-003": "assets/images/food/potato-silk.jpg",
  "canteen-004": "assets/images/food/braised-chicken-leg.jpg",
  "canteen-005": "assets/images/food/mapo-tofu.jpg",
  "canteen-006": "assets/images/food/steamed-fish.jpg",
  "canteen-007": "assets/images/food/duck-leg.jpg",
  "canteen-008": "assets/images/food/beef-noodles.jpg",
  "canteen-009": "assets/images/food/malatang.jpg",
  "canteen-010": "assets/images/food/steamed-egg.jpg",
  "canteen-011": "assets/images/food/rice.jpg",
  "canteen-012": "assets/images/food/mixed-grain-rice.jpg",
  "canteen-013": "assets/images/food/egg-drop-soup.jpg",
  "canteen-014": "assets/images/food/corn.jpg",
  "canteen-015": "assets/images/food/kung-pao-chicken.jpg",
  "canteen-016": "assets/images/food/yuxiang-pork.jpg",
  "canteen-017": "assets/images/food/braised-eggplant.jpg",
  "canteen-018": "assets/images/food/beef-potato-stew.jpg",
  "canteen-019": "assets/images/food/muxu-pork.jpg",
  "canteen-020": "assets/images/food/egg-fried-rice.jpg",
  "canteen-021": "assets/images/food/mung-bean-soup.jpg",
  "takeout-001": "assets/images/food/braised-chicken-rice.jpg",
  "takeout-002": "assets/images/food/beef-noodles.jpg",
  "takeout-003": "assets/images/food/sandwich.jpg",
  "takeout-004": "assets/images/food/spicy-malaxiangguo.jpg",
  "takeout-005": "assets/images/food/maocai.jpg",
  "takeout-006": "assets/images/food/pig-trotter-rice.jpg",
  "takeout-007": "assets/images/food/bibimbap.jpg",
  "takeout-008": "assets/images/food/burger.jpg",
  "takeout-009": "assets/images/food/duck-leg.jpg",
  "takeout-010": "assets/images/food/claypot-rice.jpg",
  "takeout-011": "assets/images/food/pickled-cabbage-fish.jpg",
  "takeout-012": "assets/images/food/chicken-pot.jpg",
  "takeout-013": "assets/images/food/burger-mcdonalds.jpg",
  "takeout-014": "assets/images/food/burger-kfc.jpg",
  "takeout-015": "assets/images/food/burger-bk.jpg",
  "takeout-016": "assets/images/food/burger-hualai.jpg",
  "takeout-017": "assets/images/food/burger-tastien.jpg",
  "takeout-018": "assets/images/food/burger-dicos.jpg",
  "supermarket-001": "assets/images/food/chicken-breast.jpg",
  "supermarket-002": "assets/images/food/yogurt-banana.jpg",
  "supermarket-003": "assets/images/food/oden.jpg",
  "supermarket-004": "assets/images/food/soy-milk.jpg",
  "supermarket-005": "assets/images/food/beef-salad.jpg",
  "supermarket-006": "assets/images/food/onigiri.jpg",
  "supermarket-007": "assets/images/food/yogurt-bowl.jpg",
  "supermarket-008": "assets/images/food/beef-salad.jpg",
  "cook-001": "assets/images/food/tomato-chicken-soba.jpg",
  "cook-002": "assets/images/food/shrimp-broccoli-rice.jpg",
  "cook-003": "assets/images/food/grilled-chicken-breast.jpg",
  "cook-004": "assets/images/food/overnight-oats.jpg",
  "cook-005": "assets/images/food/tofu-seaweed-soup.jpg",
  "cook-006": "assets/images/food/rice-cooker-chicken-rice.jpg",
  "cook-007": "assets/images/food/rice-cooker-beef-rice.jpg",
  "cook-008": "assets/images/food/milk-oat-egg.jpg",
  "cook-009": "assets/images/food/tuna-corn-salad.jpg",
  "cook-010": "assets/images/food/tomato-tofu-soup.jpg",
  "cook-011": "assets/images/food/purple-potato-egg.jpg",
  "cook-012": "assets/images/food/overnight-oats.jpg",
  "cook-013": "assets/images/food/sandwich.jpg",
  "cook-014": "assets/images/food/konjac-cucumber-shrimp.jpg",
  "cook-015": "assets/images/food/soba-egg-noodles.jpg",
  "cook-016": "assets/images/food/yogurt-bowl.jpg",
  "convenience-001": "assets/images/food/oden.jpg",
  "convenience-002": "assets/images/food/onigiri.jpg",
  "convenience-003": "assets/images/food/chicken-salad.jpg",
  "convenience-004": "assets/images/food/onigiri.jpg",
  "convenience-005": "assets/images/food/burger.jpg",
  "convenience-006": "assets/images/food/oden.jpg",
  "convenience-007": "assets/images/food/corn-cup.jpg",
  "bakery-001": "assets/images/food/bagel.jpg",
  "bakery-002": "assets/images/food/pumpkin-bread.jpg",
  "fruit-001": "assets/images/food/fruit-plate.jpg",
  "fruit-002": "assets/images/food/yogurt-bowl.jpg",
  "stall-001": "assets/images/food/grilled-cold-noodles.jpg",
  "stall-002": "assets/images/food/oden.jpg",
  "single-001": "assets/images/food/steamed-bun.jpg",
  "single-002": "assets/images/food/avocado.jpg",
  "single-003": "assets/images/food/boiled-potato.jpg",
  "single-004": "assets/images/food/boiled-egg.jpg",
  "single-005": "assets/images/food/soy-milk.jpg",
  "single-006": "assets/images/food/banana.jpg",
  "single-007": "assets/images/food/apple.jpg",
  "single-008": "assets/images/food/whole-wheat-bread.jpg",
  "single-009": "assets/images/food/milk.jpg",
  "single-010": "assets/images/food/pumpkin.jpg",
  "single-011": "assets/images/food/cucumber.jpg",
  "single-012": "assets/images/food/oatmeal.jpg"
};

for (const recipe of RECIPES) {
  if (RECIPE_FOOD_IMAGES[recipe.id]) recipe.imageUrl = RECIPE_FOOD_IMAGES[recipe.id];
}
